apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-infrastructure
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/TayyabSuhail123/k8s-argocd-ollama.git
    targetRevision: main
    path: argocd/infrastructure
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-applications
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/TayyabSuhail123/k8s-argocd-ollama.git
    targetRevision: main
    path: argocd/applications
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
