apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-apps
  namespace: argocd
spec:
  project: default
  
  source:
    # Point to your GitHub repo
    repoURL: https://github.com/TayyabSuhail123/k8s-argocd-ollama.git
    targetRevision: main
    path: argocd
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
