apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-model-loader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TayyabSuhail123/k8s-argocd-ollama.git
    targetRevision: main
    path: charts/ollama-model-loader
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
