apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  
  source:
    repoURL: https://github.com/TayyabSuhail123/k8s-argocd-ollama.git
    targetRevision: main
    path: charts/openwebui
    helm:
      releaseName: openwebui
      values: |
        # Use default values from values.yaml
        # Connects to Ollama at: http://ollama.ai-platform.svc.cluster.local:11434
        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
